name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Space cleanup
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate .config
      run: |
        touch .config
        echo 'CONFIG_TARGET_ipq53xx=y' >> .config
        echo 'CONFIG_TARGET_ipq53xx_generic=y' >> .config
        echo 'CONFIG_TARGET_ipq53xx_generic_DEVICE_jdc_be6500=y' >> .config
        echo 'CONFIG_ALL_KMODS=y' >> .config
        echo 'CONFIG_ALL_NONSHARED=y' >> .config
        echo 'CONFIG_DEVEL=y' >> .config
        echo 'CONFIG_CCACHE=y' >> .config

    - name: Build firmware
      run: |
        make defconfig
        make -j1 download
        make -j$(nproc) V=s || make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: fanchmwrt-be6500
        path: bin/targets/**/*.bin
